title: OUR.ai
description: Open User Research - A collective of professional user, market, and product researchers collaborating on AI methods, tooling, and best practices.
show_drafts: false
markdown: kramdown

remote_theme: pages-themes/minimal@v0.2.0